version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: smart-learn/php
        container_name: smart-learn-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        ports:
            - "9000:9000"
        environment:
            VITE_APP_NAME: "${APP_NAME}"
            VITE_APP_ENV: "${APP_ENV}"
            VITE_APP_URL: "${APP_URL}"
            VITE_APP_PORT: "${APP_PORT}"
        networks:
            - smart-learn-network

    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        image: smart-learn/nginx
        container_name: smart-learn-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - smart-learn-network
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: smart-learn-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_USER: "${DB_USERNAME}"
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - smart-learn-db-data:/var/lib/mysql
        networks:
            - smart-learn-network
        ports:
            - "3306:3306"

    redis:
        image: redis:alpine
        container_name: smart-learn-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - smart-learn-network

networks:
    smart-learn-network:
        driver: bridge

volumes:
    smart-learn-db-data:
        driver: local
